### ISSUE TITLE
Doc: User State Migration (JS)

### ISSUE THREAD

**Issue by scheyal** [scheyal/BotV3V4Migration#16]

**Comment by mmiele** [comment]
Work in progress.

**Comment by mmiele** [comment]
Jonathan, updated the "Using JavaScript v3 user state in a v4 bot" topic. 
Please, look at the staged doc at the doc PR MicrosoftDocs/bot-docs-pr#1656. 
Give me your feedback so we can close the issue.
I need the link to the published code, so I can link directly from the document.
Thanks,
Michael

**Comment by EricDahlvang** [comment]
@mmiele  The code for Jonathan's sample can be found here: https://github.com/microsoft/BotBuilder-Samples/tree/master/MigrationV3V4/Node/V4V3-user-state-adapter-sample-bot

**Comment by mmiele** [comment]
Work in progress.
See https://github.com/MicrosoftDocs/bot-docs-pr/pull/1656

**Comment by EricDahlvang** [comment]
Lgtm

**Comment by mmiele** [comment]
@jspruance. Pulled he updated document from the doc build. Saved a copy. Let me know when we are ready to publish it. Thanks
