### ISSUE TITLE
Sample: User State Migration (C#)

### ISSUE THREAD

**Issue by scheyal** [scheyal/BotV3V4Migration#25]

**Comment by EricDahlvang** [comment]
https://github.com/microsoft/BotBuilder-Samples/pull/1573

**Comment by EricDahlvang** [comment]
Closing... the PR has been accepted and merged: https://github.com/microsoft/BotBuilder-Samples/pull/1573

**Comment by scheyal** [comment]
update corresponding documentation

**Comment by mmiele** [comment]
Add information to this topic: [.NET migration quick reference](https://docs.microsoft.com/en-us/azure/bot-service/migration/net-migration-quickreference?view=azure-bot-service-4.0).

**Comment by EricDahlvang** [comment]
I don't think this will be a Quick Reference, considering the users will be expected to download this project: https://github.com/microsoft/BotBuilder-Samples/tree/master/MigrationV3V4/CSharp/V4StateBotFromV3Providers/Bot.Builder.Azure.V3ToV4  and include it in their V4 bot's source code.

**Comment by mmiele** [comment]
Still not completely familiar with the doc set. 
Where do you suggest this info is going to be located?

**Comment by EricDahlvang** [comment]
Based on the complexity of this, I think it should be its own page.  @jspruance  is working on the node portion for this right now.  I don't know what he will have when he is finished, but the final .net method for interacting with v3 UserData in a v4 bot is complex enough to warrant a detailed explanation.
