### ISSUE TITLE
Add Migration Estimation Worksheet to docs (C#)

### ISSUE THREAD

**Issue by EricDahlvang** [scheyal/BotV3V4Migration#28]
S.NO | Command /details | V3 | V4 | Detected Occurrences | Complexity | T-Shirt Size*
-- | -- | -- | -- | -- | -- | --
1 | To get the incoming activity | IDialogContext.Activity | ITurnContext.Activity | count | Simple |  
2 | To create and send an activity to the user | activity.CreateReply(“text”) IDialogContext.PostAsync | MessageFactory.Text(“text”) ITurnContext.SendActivityAsync | count | Simple |  
3 | State management | UserData, ConversationData, and PrivateConversationData context.UserData.SetValue context.UserData.TryGetValue botDataStore.LoadAsyn | UserState, ConversationState, and PrivateConversationState  With property accessors | context.UserData.SetValue - count context.UserData.TryGetValue - count botDataStore.LoadAsyn - count | Medium to Large (User State solution available) |  
4 | Handle the start of your dialog | Implement IDialog.StartAsync | Make this the first step of a waterfall dialog. | <count | Simple |  
5 | Send an activity | IDialogContext.PostAsync. | Call ITurnContext.SendActivityAsync. | count | Simple |  
6 | Wait for a user's response | Use an IAwaitable<IMessageActivity>parameter and call IDialogContext.Wait | Return await ITurnContext.PromptAsync to begin a prompt dialog. Then retrieve the result in the next step of the waterfall. | count | Medium (depends on flow) |  
7 | Handle continuation of your dialog | IDialogContext.Wait | Add additional steps to a waterfall dialog, or implement Dialog.ContinueDialogAsync | count | Large |  
8 | Signal the end of processing until the user's next message | IDialogContext.Wait | Return Dialog.EndOfTurn. | count | Medium |  
9 | Begin a child dialog | IDialogContext.Call | Return await the step context's BeginDialogAsyncmethod. If the child dialog returns a value, that value is available in the next step of the waterfall via the step context's Resultproperty. | count | Medium |  
10 | Replace the current dialog with a new dialog | IDialogContext.Forward | Return await ITurnContext.ReplaceDialogAsync. | count | Large |  
11 | Signal that the current dialog has completed | IDialogContext.Done | Return await the step context's EndDialogAsync method. | count | Medium |  
12 | Fail out of a dialog. | IDialogContext.Fail | Throw an exception to be caught at another level of the bot, end the step with a status of Cancelled, or call the step or dialog context's CancelAllDialogsAsync. | count | Simple |  

https://github.com/scheyal/BotV3V4Migration/issues/28

**Comment by mmiele** [comment]
Added worksheet to the work in progress topic: **Migration overview**. Tech review pending.

**Comment by mmiele** [comment]
Migration Estimation Worksheet added to the **Migration overview** article.
