### ISSUE TITLE
Migration Estimation Worksheet (JS)

### ISSUE THREAD

**Issue by EricDahlvang** [scheyal/BotV3V4Migration#29]
ref: https://github.com/scheyal/BotV3V4Migration/issues/28

**Comment by jspruance** [comment]
Content complete - handed off to Michael for formatting.

**Comment by mmiele** [comment]
Jonathan, revised and updated the "Migration overview" topic. Please, look at the staged doc at the doc PR https://github.com/MicrosoftDocs/bot-docs-pr/pull/1656. Give me your feedback so we can close the issue.

**Comment by mmiele** [comment]
Work in progress.
See https://github.com/MicrosoftDocs/bot-docs-pr/pull/1656

**Comment by mmiele** [comment]
@jspruance. Made the requested fixes. The updated document will be in the next doc build. Thanks
