### ISSUE TITLE
Add Custom Recognizer sample for DotNet

### ISSUE THREAD

**Issue by scheyal** [scheyal/BotV3V4Migration#37]

**Comment by scheyal** [comment]
assess work/need.

**Comment by EricDahlvang** [comment]
I don't think this applies to dotnet v3, but only javascript v3.  The v3 node sdk used the concept of 'recognizers' heavily, but in dotnet, we only had https://github.com/microsoft/BotBuilder-V3/blob/master/CSharp/Library/Microsoft.Bot.Builder/Dialogs/PromptRecognizer.cs

**Comment by scheyal** [comment]
won't fix.
