### ISSUE TITLE
Doc roadmap plan (how far are we from 100%, what do we need to get to 100%)

### ISSUE THREAD

**Issue by scheyal** [scheyal/BotV3V4Migration#4]

**Comment by JonathanFingold** [comment]
@scheyal , Please review the [Documentation roadmap](https://microsoft.sharepoint.com/teams/ConversationalAI785/_layouts/15/WopiFrame.aspx?sourcedoc={c63e1300-da6b-4682-9ad6-400fd3a7dd56}&action=edit&wd=target%28PM.one%7C67355280-3dbf-4364-8f4b-101757b6a7f8%2FDocumentation%20check-list%7Cb2b24090-6a6d-4060-b6a2-38faedf55b83%2F%29)
